# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# Add or remove your plugins here:
[[plugins]] # カラースキーム
repo = 'cocopon/iceberg.vim'
hook_add = '''
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nested を付ける。
  au MyAutoCmd VimEnter * nested colorscheme iceberg
'''

[[plugins]] # deniteの前提プラグイン
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if has('win32')
    let cmd = 'tools\\update-dll-mingw'
  elseif has('win32unix') " for Cygwin
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]] # neosnippetの前提プラグイン
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # vim8使用時のdeoplete前提プラグイン
repo = 'roxma/nvim-yarp'

[[plugins]] # vim8使用時のdeoplete前提プラグイン
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]] # gitプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]] # 閉じ括弧、2個目のクォーテーションを自動入力
repo = 'cohama/lexima.vim'

[[plugins]] # 行末スペースの可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # カーソル移動高速化
repo = 'easymotion/vim-easymotion'
hook_add = '''
  map <Leader> <Plug>(easymotion-prefix)
'''

[[plugins]] # ctags作成
repo = 'soramugi/auto-ctags.vim'

[[plugins]] # コメント化/コメント解除
repo = 'tpope/vim-commentary.git'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # ステータスラインの表示を強化
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ 'active': {
    \   'left': [
    \   [ 'mode', 'paste' ],
    \   [ 'gitbranch', 'readonly', 'filename', 'modified' ]
    \ ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'fugitive#head',
    \   'filename': 'LightlineFilename'
    \ }
    \ }

  function! LightlineFilename()
    return '' != expand('%:t') ? expand('%:t') : '[No Name]'
  endfunction
'''
depends = ['vim-fugitive']

[[plugins]] # Gitとの差分を表示する
repo = 'airblade/vim-gitgutter'

[[plugins]] # レジスタの履歴を取得・再利用
repo = 'LeafCage/yankround.vim'
hook_add = '''
	nmap p <Plug>(yankround-p)
	xmap p <Plug>(yankround-p)
	nmap P <Plug>(yankround-P)
	nmap gp <Plug>(yankround-gp)
	xmap gp <Plug>(yankround-gp)
	nmap gP <Plug>(yankround-gP)
	nmap <C-p> <Plug>(yankround-prev)
	nmap <C-n> <Plug>(yankround-next)
'''

[[plugins]] # ヘルプを日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # 括弧の対応をカラーリング
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
'''
