[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]] # ファイル選択
repo = 'Shougo/denite.nvim'
depends = ['vimproc.vim']
hook_add = '''
  " バッファ一覧
  noremap <C-p> :Denite buffer<CR>
  " ファイル一覧
  noremap <C-n> :Denite -buffer-name=file file<CR>
  " 最近使ったファイルの一覧
  noremap <C-z> :Denite file_old<CR>
  " カレントディレクトリ
  noremap <C-c> :Denite file_rec<CR>
  " denite grep
  noremap <C-f> :Denite grep<CR>
'''
hook_post_source = '''
  " grepをagに変更
  if executable('ag')
    call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-u', '-g', ''])
    call denite#custom#var('grep', 'command', ['ag'])
    call denite#custom#var('grep', 'recursive_opts', [])
    call denite#custom#var('grep', 'pattern_opt', [])
    call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
  endif
'''

